/**
 * Writes src/app/tokens.css from the widget's design tokens (web/widget/src/tokens.ts), the
 * single source of truth for colours, radii, spacing, shadows, type and motion. Run with
 * `npm run tokens`; tests/tokens.test.ts fails if the CSS is out of date.
 */
import { writeFileSync } from "node:fs";
import { tokensCss } from "../../widget/src/tokens.ts";

export const TOKENS_HEADER =
  "/* Generated by scripts/sync-tokens.ts from web/widget/src/tokens.ts. Do not edit. */\n";

export function tokensFile(): string {
  return `${TOKENS_HEADER}${tokensCss(":root").replaceAll(";", ";\n  ").replace("{", "{\n  ").replace(/\s+}$/, "\n}")}\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL("../src/app/tokens.css", import.meta.url), tokensFile());
  console.warn("wrote src/app/tokens.css");
}
